version: '3.6'

networks:
  network:
    driver: overlay
    attachable: true

volumes:
  gem-cache:
    external: false
  mysql-data:
    external: false

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - network
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT:-33066}:3306
    environment:
      MYSQL_USER: ${DB_USERNAME:-stoam}
      MYSQL_PASSWORD: ${DB_PASSWORD:-stoam}
      MYSQL_DATABASE: ${DB_DATABASE:-stoam_development}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-stoam}
      MYSQL_TEST_DATABASE: ${DB_TEST_DATABASE:-stoam_test}

  ruby:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args: 
        USER: stoam
        UID: $USER_ID
        GID: $GROUP_ID
    stdin_open: true
    tty: true
    command: >
      sh -c "(bundle check || bundle install) && touch /var/app/tmp/pids/server.pid && rm /var/app/tmp/pids/server.pid || true  && bundle exec rails s -b 0.0.0.0 -p 3030"
    volumes:
      - gem-cache:/usr/local/bundle:delegated
      - ../:/var/app
    ports:
      - ${APP_PORT:-3000}:3030
      - 3035:3035
    depends_on:
      - mysql
    networks:
      - network
    environment:
      APP_DATABASE_HOST: mysql
      APP_DATABASE_USERNAME: ${DB_USERNAME:-stoam}
      APP_DATABASE_PASSWORD: ${DB_PASSWORD:-stoam}
  
  # elasticsearch:
  #   image: elasticsearch:6.8.12
  #   networks:
  #     - network
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  # mailhog:
  #   image: mailhog/mailhog
  #   networks:
  #     - network
  #   ports:
  #     - 8025:8025